title: Herman Justino
author: Herman Justino
email: hermanjustino@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My personal website and portfolio

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
